# Site settings
exclude: [README.md,example1.md,example2.md]
title: Lena Voita
email: lena-voita@hotmail.com
github: lena-voita
twitter: lena_voita
scholar_id: EcN9o7kAAAAJ
description: > # this symbol means ignore newlines until "baseurl:"
    Hi! I'm Lena and here you will find what I do.
baseurl: "" # keep blank unless you're using sub-paths
url: "http://lena-voita.github.io" # the base hostname & protocol for your site
#paginate: 3

# you can also declare arbitrary key-value data here
uva_url_lena: "https://msclogic.illc.uva.nl/people/students/"
uva_url_main: "https://www.illc.uva.nl"
edn_nlp_people: "https://edinburghnlp.inf.ed.ac.uk/index.php/people/"
edn_nlp_main: "http://edinburghnlp.inf.ed.ac.uk"
school_of_informatics: "https://www.ed.ac.uk/informatics"
yandex_research_people: "https://research.yandex.com/people/"
yandex_research_main: "https://research.yandex.com"

ivan_page: "http://ivan-titov.org"
rico_page: "http://homepages.inf.ed.ac.uk/rsennric/"


# Build settings
markdown: kramdown
